
// Site data
export const siteData = {
  base: '/',
  title: 'LDoc 演示站点',
  description: '现代化文档系统演示',
  lang: 'zh-CN',
  themeConfig: {"logo":"https://wuhan.yxybb.com/ldesign/source/npm-logo.svg","siteTitle":"LDesign","layout":{"sidebarWidth":260,"outlineWidth":220,"contentGap":32,"navHeight":64,"maxWidth":1400},"nav":[{"text":"指南","link":"/guide/"},{"text":"示例","link":"/examples/"},{"text":"API","link":"/api/"},{"text":"插件","link":"/plugins/"},{"text":"源码示例","link":"/src-demo"},{"text":"GitHub","link":"https://github.com/polyester-design/ldesign"}],"sidebar":{"/guide/":[{"text":"开始使用","items":[{"text":"介绍","link":"/guide/"},{"text":"快速开始","link":"/guide/getting-started"},{"text":"配置","link":"/guide/configuration"}]},{"text":"编写文档","items":[{"text":"Markdown 扩展","link":"/guide/markdown"},{"text":"Frontmatter","link":"/guide/frontmatter"},{"text":"静态资源","link":"/guide/assets"}]},{"text":"进阶","items":[{"text":"主题定制","link":"/guide/theme"},{"text":"国际化","link":"/guide/i18n"},{"text":"部署","link":"/guide/deploy"}]}],"/api/":[{"text":"API 参考","items":[{"text":"概述","link":"/api/"},{"text":"站点配置","link":"/api/site-config"},{"text":"主题配置","link":"/api/theme-config"},{"text":"Frontmatter","link":"/api/frontmatter"}]},{"text":"客户端 API","items":[{"text":"Composables","link":"/api/composables"},{"text":"组件","link":"/api/components"}]}],"/examples/":[{"text":"功能示例","items":[{"text":"示例总览","link":"/examples/"}]},{"text":"Markdown 增强","items":[{"text":"代码块","link":"/examples/markdown/code"},{"text":"容器与扩展","link":"/examples/markdown/containers"}]},{"text":"容器与提示","items":[{"text":"信息容器","link":"/examples/containers/"}]},{"text":"媒体资源","items":[{"text":"图片展示","link":"/examples/media/images"},{"text":"视频嵌入","link":"/examples/media/videos"},{"text":"图标使用","link":"/examples/media/icons"}]},{"text":"Vue 组件","items":[{"text":"基础组件","link":"/examples/vue/basic"},{"text":"交互组件","link":"/examples/vue/interactive"}]},{"text":"高级功能","items":[{"text":"数学公式","link":"/examples/advanced/math"},{"text":"流程图","link":"/examples/advanced/diagrams"}]}],"/plugins/":[{"text":"插件系统","items":[{"text":"概述","link":"/plugins/"},{"text":"使用插件","link":"/plugins/using"}]},{"text":"内置插件","items":[{"text":"组件演示插件","link":"/plugins/demo"},{"text":"搜索插件","link":"/plugins/search"},{"text":"评论插件","link":"/plugins/comment"},{"text":"进度条插件","link":"/plugins/progress"},{"text":"代码复制插件","link":"/plugins/copy-code"},{"text":"图片预览插件","link":"/plugins/image-viewer"},{"text":"阅读时间插件","link":"/plugins/reading-time"},{"text":"最后更新插件","link":"/plugins/last-updated"}]},{"text":"开发插件","items":[{"text":"插件开发指南","link":"/plugins/development"},{"text":"插件 API","link":"/plugins/api"}]},{"text":"开发主题","items":[{"text":"主题开发指南","link":"/plugins/theme-dev"}]}]},"socialLinks":[{"icon":"github","link":"https://github.com/nicepkg/ldesign"}],"footer":{"message":"基于 MIT 许可发布","copyright":"版权所有 © 2024 LDesign"},"editLink":{"pattern":"https://github.com/nicepkg/ldesign/edit/main/docs/:path","text":"在 GitHub 上编辑此页"},"lastUpdated":{"text":"最后更新"},"outline":{"level":[1,6],"label":"本页目录"}},
  locales: {"root":{"label":"简体中文","lang":"zh-CN"},"en":{"label":"English","lang":"en-US","link":"/en/","themeConfig":{"nav":[{"text":"Guide","link":"/en/guide/"},{"text":"Examples","link":"/en/examples/"},{"text":"API","link":"/en/api/"},{"text":"Plugins","link":"/en/plugins/"},{"text":"GitHub","link":"https://github.com/polyester-design/ldesign"}]}}},
  head: []
}
