/**
 * EPUB 导出功能
 * 使用 epub-gen-memory 生成 EPUB 文件
 */

import type { EPUBConfig } from './index'

/**
 * EPUB 导出选项
 */
export interface EPUBExportOptions extends EPUBConfig {
  /** 要导出的页面内容 */
  pages: EPUBPage[]
  /** 输出文件路径 */
  output: string
  /** CSS 样式 */
  css?: string
  /** 字体文件 */
  fonts?: string[]
  /** 是否包含目录 */
  toc?: boolean
}

/**
 * EPUB 页面内容
 */
export interface EPUBPage {
  /** 页面标题 */
  title: string
  /** 页面内容（HTML） */
  content: string
  /** 页面 URL（用于获取内容） */
  url?: string
  /** 页面作者 */
  author?: string
  /** 是否排除在目录外 */
  excludeFromToc?: boolean
  /** 页面文件名 */
  filename?: string
}

/**
 * EPUB 元数据
 */
interface EPUBMetadata {
  title: string
  author: string
  language: string
  cover?: string
  description?: string
  publisher?: string
  published?: string
  modified?: string
}

/**
 * 导出为 EPUB
 * 
 * @param options EPUB 导出选项
 * @returns Promise<void>
 * 
 * @example
 * ```ts
 * await exportToEPUB({
 *   pages: [
 *     { title: 'Introduction', content: '<h1>Introduction</h1><p>...</p>' },
 *     { title: 'Getting Started', content: '<h1>Getting Started</h1><p>...</p>' }
 *   ],
 *   output: './output/documentation.epub',
 *   title: 'My Documentation',
 *   author: 'John Doe',
 *   language: 'en'
 * })
 * ```
 */
export async function exportToEPUB(options: EPUBExportOptions): Promise<void> {
  const {
    pages,
    output,
    title = 'Documentation',
    author = 'Unknown',
    language = 'en',
    cover,
    css,
    fonts = [],
    toc = true
  } = options

  // 验证输入
  if (!pages || pages.length === 0) {
    throw new Error('At least one page is required for EPUB export')
  }

  // 动态导入 epub-gen-memory
  let EPub: any
  try {
    const epubModule = await import('epub-gen-memory')
    EPub = epubModule.default || epubModule
  } catch (error) {
    throw new Error(
      'epub-gen-memory is not installed. Please install it with: npm install -D epub-gen-memory'
    )
  }

  // 准备元数据
  const metadata: EPUBMetadata = {
    title,
    author,
    language,
    cover,
    description: `${title} - Generated by @ldesign/doc`,
    publisher: '@ldesign/doc',
    published: new Date().toISOString(),
    modified: new Date().toISOString()
  }

  // 准备章节内容
  const content = pages.map((page, index) => ({
    title: page.title,
    data: sanitizeHTML(page.content),
    author: page.author || author,
    excludeFromToc: page.excludeFromToc || false,
    filename: page.filename || `chapter-${index + 1}.xhtml`
  }))

  // 准备 EPUB 选项
  const epubOptions = {
    ...metadata,
    content,
    css: css || getDefaultEPUBStyles(),
    fonts,
    tocTitle: toc ? 'Table of Contents' : undefined,
    appendChapterTitles: true,
    verbose: false
  }

  try {
    // 生成 EPUB
    const epub = new EPub(epubOptions, output)
    await epub.promise

    // 验证生成的 EPUB
    await validateEPUB(output)
  } catch (error) {
    throw new Error(
      `Failed to generate EPUB: ${error instanceof Error ? error.message : String(error)}`
    )
  }
}

/**
 * 清理 HTML 内容，确保 EPUB 兼容性
 */
function sanitizeHTML(html: string): string {
  // 移除不必要的脚本和样式
  let sanitized = html
    .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '')
    .replace(/<style\b[^<]*(?:(?!<\/style>)<[^<]*)*<\/style>/gi, '')

  // 确保所有图片有 alt 属性
  sanitized = sanitized.replace(/<img([^>]*?)>/gi, (match, attrs) => {
    if (!attrs.includes('alt=')) {
      return `<img${attrs} alt="">`
    }
    return match
  })

  // 移除内联事件处理器
  sanitized = sanitized.replace(/\s+on\w+="[^"]*"/gi, '')

  // 确保所有标签正确闭合
  sanitized = sanitized
    .replace(/<br\s*>/gi, '<br/>')
    .replace(/<hr\s*>/gi, '<hr/>')
    .replace(/<img([^>]*?)(?<!\/)>/gi, '<img$1/>')

  return sanitized
}

/**
 * 获取默认 EPUB 样式
 */
function getDefaultEPUBStyles(): string {
  return `
/* EPUB 默认样式 */
body {
  font-family: Georgia, serif;
  font-size: 1em;
  line-height: 1.6;
  margin: 1em;
  color: #000;
  background: #fff;
}

h1, h2, h3, h4, h5, h6 {
  font-family: Arial, sans-serif;
  font-weight: bold;
  margin-top: 1.5em;
  margin-bottom: 0.5em;
  line-height: 1.3;
  page-break-after: avoid;
}

h1 { font-size: 2em; }
h2 { font-size: 1.5em; }
h3 { font-size: 1.3em; }
h4 { font-size: 1.1em; }
h5 { font-size: 1em; }
h6 { font-size: 0.9em; }

p {
  margin: 0.5em 0;
  text-align: justify;
  orphans: 2;
  widows: 2;
}

code {
  font-family: 'Courier New', monospace;
  font-size: 0.9em;
  background: #f5f5f5;
  padding: 0.2em 0.4em;
  border-radius: 3px;
}

pre {
  font-family: 'Courier New', monospace;
  font-size: 0.85em;
  background: #f5f5f5;
  padding: 1em;
  border-radius: 5px;
  overflow-x: auto;
  page-break-inside: avoid;
}

pre code {
  background: none;
  padding: 0;
}

blockquote {
  margin: 1em 2em;
  padding: 0.5em 1em;
  border-left: 4px solid #ddd;
  font-style: italic;
  color: #666;
}

ul, ol {
  margin: 0.5em 0;
  padding-left: 2em;
}

li {
  margin: 0.3em 0;
}

table {
  width: 100%;
  border-collapse: collapse;
  margin: 1em 0;
  page-break-inside: avoid;
}

th, td {
  border: 1px solid #ddd;
  padding: 0.5em;
  text-align: left;
}

th {
  background: #f5f5f5;
  font-weight: bold;
}

img {
  max-width: 100%;
  height: auto;
  display: block;
  margin: 1em auto;
  page-break-inside: avoid;
}

a {
  color: #0066cc;
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}

hr {
  border: none;
  border-top: 1px solid #ddd;
  margin: 2em 0;
}

.page-break {
  page-break-after: always;
}
`.trim()
}

/**
 * 验证 EPUB 文件结构
 */
async function validateEPUB(filepath: string): Promise<void> {
  const { existsSync, statSync } = await import('node:fs')

  // 检查文件是否存在
  if (!existsSync(filepath)) {
    throw new Error(`EPUB file not found: ${filepath}`)
  }

  // 检查文件大小
  const stats = statSync(filepath)
  if (stats.size === 0) {
    throw new Error('Generated EPUB file is empty')
  }

  // 基本验证：EPUB 是 ZIP 文件，应该以 PK 开头
  const { readFileSync } = await import('node:fs')
  const buffer = readFileSync(filepath)
  const header = buffer.slice(0, 2).toString('hex')

  if (header !== '504b') {
    throw new Error('Generated file is not a valid EPUB (invalid ZIP header)')
  }
}

/**
 * 从 URL 获取页面内容并导出为 EPUB
 * 
 * @param urls 页面 URL 数组
 * @param output 输出文件路径
 * @param options EPUB 配置
 * @returns Promise<void>
 * 
 * @example
 * ```ts
 * await exportURLsToEPUB(
 *   [
 *     'http://localhost:5173/guide/intro',
 *     'http://localhost:5173/guide/setup'
 *   ],
 *   './output/guide.epub',
 *   {
 *     title: 'User Guide',
 *     author: 'Documentation Team'
 *   }
 * )
 * ```
 */
export async function exportURLsToEPUB(
  urls: string[],
  output: string,
  options: EPUBConfig = {}
): Promise<void> {
  // 动态导入 Playwright
  let playwright: any
  try {
    playwright = await import('playwright')
  } catch (error) {
    throw new Error(
      'Playwright is not installed. Please install it with: npm install -D playwright'
    )
  }

  const browser = await playwright.chromium.launch({ headless: true })
  const pages: EPUBPage[] = []

  try {
    const context = await browser.newContext()

    for (const url of urls) {
      const page = await context.newPage()

      try {
        await page.goto(url, { waitUntil: 'networkidle' })

        // 提取页面标题和内容
        const pageData = await page.evaluate(() => {
          const titleEl = document.querySelector('h1') || document.querySelector('title')
          const title = titleEl?.textContent?.trim() || 'Untitled'

          // 获取主要内容区域
          const contentEl = document.querySelector('.vp-doc') || document.querySelector('main') || document.body
          const content = contentEl?.innerHTML || ''

          return { title, content }
        })

        pages.push({
          title: pageData.title,
          content: pageData.content,
          url
        })
      } finally {
        await page.close()
      }
    }

    // 导出为 EPUB
    await exportToEPUB({
      pages,
      output,
      ...options
    })
  } finally {
    await browser.close()
  }
}

/**
 * 验证 EPUB 配置
 */
export function validateEPUBConfig(config: EPUBConfig): boolean {
  // 验证语言代码格式
  if (config.language !== undefined) {
    if (!config.language || !/^[a-z]{2}(-[A-Z]{2})?$/.test(config.language)) {
      return false
    }
  }

  // 验证封面路径
  if (config.cover !== undefined) {
    if (!config.cover || typeof config.cover !== 'string') {
      return false
    }
  }

  return true
}
