/**
 * 单页 HTML 导出功能
 * 将多个页面合并为单个 HTML 文件
 */

import type { HTMLConfig } from './index'

/**
 * 单页导出选项
 */
export interface SinglePageExportOptions extends HTMLConfig {
  /** 要导出的页面 */
  pages: PageContent[]
  /** 输出文件路径 */
  output: string
  /** 文档标题 */
  title?: string
  /** 基础 URL（用于修复相对链接） */
  baseUrl?: string
}

/**
 * 页面内容
 */
export interface PageContent {
  /** 页面标题 */
  title: string
  /** 页面内容（HTML） */
  content: string
  /** 页面 ID（用于锚点） */
  id?: string
  /** 页面 URL（原始 URL） */
  url?: string
}

/**
 * 导出为单页 HTML
 * 
 * @param options 单页导出选项
 * @returns Promise<void>
 * 
 * @example
 * ```ts
 * await exportToSinglePage({
 *   pages: [
 *     { title: 'Introduction', content: '<h1>Intro</h1><p>...</p>', id: 'intro' },
 *     { title: 'Getting Started', content: '<h1>Start</h1><p>...</p>', id: 'start' }
 *   ],
 *   output: './output/documentation.html',
 *   title: 'My Documentation',
 *   inlineStyles: true
 * })
 * ```
 */
export async function exportToSinglePage(options: SinglePageExportOptions): Promise<void> {
  const {
    pages,
    output,
    title = 'Documentation',
    inlineStyles = true,
    inlineImages = false,
    baseUrl
  } = options

  // 验证输入
  if (!pages || pages.length === 0) {
    throw new Error('At least one page is required for single-page export')
  }

  // 生成页面 ID
  const pagesWithIds = pages.map((page, index) => ({
    ...page,
    id: page.id || `page-${index + 1}`
  }))

  // 修复内部链接
  const processedPages = pagesWithIds.map(page => ({
    ...page,
    content: fixInternalLinks(page.content, pagesWithIds, baseUrl)
  }))

  // 生成目录
  const toc = generateTableOfContents(processedPages)

  // 生成完整 HTML
  const html = generateHTML({
    title,
    toc,
    pages: processedPages,
    inlineStyles,
    inlineImages
  })

  // 写入文件
  const { writeFileSync, mkdirSync } = await import('node:fs')
  const { dirname } = await import('node:path')

  // 确保输出目录存在
  mkdirSync(dirname(output), { recursive: true })

  // 写入 HTML
  writeFileSync(output, html, 'utf-8')
}

/**
 * 修复内部链接为锚点
 */
function fixInternalLinks(
  content: string,
  pages: (PageContent & { id: string })[],
  baseUrl?: string
): string {
  let fixed = content

  // 创建 URL 到 ID 的映射
  const urlToId = new Map<string, string>()
  pages.forEach(page => {
    if (page.url) {
      urlToId.set(page.url, page.id)
      // 也处理不带协议的 URL
      const withoutProtocol = page.url.replace(/^https?:\/\//, '')
      urlToId.set(withoutProtocol, page.id)
    }
  })

  // 替换内部链接为锚点
  fixed = fixed.replace(
    /<a\s+([^>]*?)href=["']([^"']+)["']([^>]*)>/gi,
    (match, before, href, after) => {
      // 检查是否是内部链接
      const cleanHref = href.replace(/^https?:\/\//, '')

      if (urlToId.has(href) || urlToId.has(cleanHref)) {
        const id = urlToId.get(href) || urlToId.get(cleanHref)
        return `<a ${before}href="#${id}"${after}>`
      }

      // 如果有 baseUrl，修复相对链接
      if (baseUrl && !href.startsWith('http') && !href.startsWith('#')) {
        const absoluteUrl = new URL(href, baseUrl).href
        return `<a ${before}href="${absoluteUrl}"${after}>`
      }

      return match
    }
  )

  return fixed
}

/**
 * 生成目录
 */
function generateTableOfContents(pages: (PageContent & { id: string })[]): string {
  const items = pages.map(page => {
    const title = escapeHTML(page.title)
    return `<li><a href="#${page.id}">${title}</a></li>`
  })

  return `
<nav class="toc">
  <h2>Table of Contents</h2>
  <ul>
    ${items.join('\n    ')}
  </ul>
</nav>
  `.trim()
}

/**
 * 生成完整 HTML 文档
 */
function generateHTML(options: {
  title: string
  toc: string
  pages: (PageContent & { id: string })[]
  inlineStyles: boolean
  inlineImages: boolean
}): string {
  const { title, toc, pages, inlineStyles } = options

  const styles = inlineStyles ? `<style>${getDefaultStyles()}</style>` : ''

  const pagesSections = pages.map(page => {
    const pageTitle = escapeHTML(page.title)
    return `
<section id="${page.id}" class="page-section">
  <h1 class="page-title">${pageTitle}</h1>
  <div class="page-content">
    ${page.content}
  </div>
</section>
    `.trim()
  })

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHTML(title)}</title>
  ${styles}
</head>
<body>
  <div class="container">
    <header>
      <h1 class="doc-title">${escapeHTML(title)}</h1>
    </header>
    
    ${toc}
    
    <main class="content">
      ${pagesSections.join('\n\n      ')}
    </main>
    
    <footer>
      <p>Generated by @ldesign/doc</p>
    </footer>
  </div>
  
  <script>
    // 平滑滚动到锚点
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
      anchor.addEventListener('click', function (e) {
        e.preventDefault();
        const target = document.querySelector(this.getAttribute('href'));
        if (target) {
          target.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
      });
    });
  </script>
</body>
</html>
  `.trim()
}

/**
 * 获取默认样式
 */
function getDefaultStyles(): string {
  return `
/* 单页文档样式 */
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
  font-size: 16px;
  line-height: 1.6;
  color: #333;
  background: #f5f5f5;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  background: #fff;
  box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
}

header {
  background: #2c3e50;
  color: #fff;
  padding: 2rem;
  text-align: center;
}

.doc-title {
  font-size: 2.5rem;
  font-weight: 700;
  margin: 0;
}

.toc {
  background: #ecf0f1;
  padding: 2rem;
  border-bottom: 2px solid #bdc3c7;
}

.toc h2 {
  font-size: 1.5rem;
  margin-bottom: 1rem;
  color: #2c3e50;
}

.toc ul {
  list-style: none;
  padding-left: 0;
}

.toc li {
  margin: 0.5rem 0;
}

.toc a {
  color: #3498db;
  text-decoration: none;
  font-size: 1.1rem;
  transition: color 0.2s;
}

.toc a:hover {
  color: #2980b9;
  text-decoration: underline;
}

.content {
  padding: 2rem;
}

.page-section {
  margin-bottom: 4rem;
  padding-bottom: 2rem;
  border-bottom: 1px solid #ecf0f1;
}

.page-section:last-child {
  border-bottom: none;
}

.page-title {
  font-size: 2rem;
  color: #2c3e50;
  margin-bottom: 1.5rem;
  padding-bottom: 0.5rem;
  border-bottom: 3px solid #3498db;
}

.page-content h1,
.page-content h2,
.page-content h3,
.page-content h4,
.page-content h5,
.page-content h6 {
  margin-top: 1.5rem;
  margin-bottom: 1rem;
  color: #2c3e50;
}

.page-content h1 { font-size: 1.8rem; }
.page-content h2 { font-size: 1.5rem; }
.page-content h3 { font-size: 1.3rem; }
.page-content h4 { font-size: 1.1rem; }

.page-content p {
  margin: 1rem 0;
  text-align: justify;
}

.page-content a {
  color: #3498db;
  text-decoration: none;
}

.page-content a:hover {
  text-decoration: underline;
}

.page-content code {
  font-family: 'Courier New', Courier, monospace;
  font-size: 0.9em;
  background: #f8f8f8;
  padding: 0.2em 0.4em;
  border-radius: 3px;
  border: 1px solid #e1e1e1;
}

.page-content pre {
  background: #f8f8f8;
  padding: 1rem;
  border-radius: 5px;
  border: 1px solid #e1e1e1;
  overflow-x: auto;
  margin: 1rem 0;
}

.page-content pre code {
  background: none;
  border: none;
  padding: 0;
}

.page-content blockquote {
  margin: 1rem 0;
  padding: 0.5rem 1rem;
  border-left: 4px solid #3498db;
  background: #ecf0f1;
  font-style: italic;
}

.page-content ul,
.page-content ol {
  margin: 1rem 0;
  padding-left: 2rem;
}

.page-content li {
  margin: 0.5rem 0;
}

.page-content table {
  width: 100%;
  border-collapse: collapse;
  margin: 1rem 0;
}

.page-content th,
.page-content td {
  border: 1px solid #ddd;
  padding: 0.75rem;
  text-align: left;
}

.page-content th {
  background: #f8f8f8;
  font-weight: 600;
}

.page-content img {
  max-width: 100%;
  height: auto;
  display: block;
  margin: 1rem auto;
  border-radius: 5px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

footer {
  background: #ecf0f1;
  padding: 1.5rem;
  text-align: center;
  color: #7f8c8d;
  font-size: 0.9rem;
}

/* 打印样式 */
@media print {
  body {
    background: #fff;
  }

  .container {
    box-shadow: none;
  }

  .toc {
    page-break-after: always;
  }

  .page-section {
    page-break-inside: avoid;
  }

  .page-title {
    page-break-after: avoid;
  }

  a[href]:after {
    content: " (" attr(href) ")";
    font-size: 0.8em;
    color: #666;
  }

  a[href^="#"]:after {
    content: "";
  }
}
  `.trim()
}

/**
 * 转义 HTML 特殊字符
 */
function escapeHTML(text: string): string {
  const map: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;'
  }
  return text.replace(/[&<>"']/g, m => map[m])
}

/**
 * 从 URL 获取页面内容并导出为单页 HTML
 * 
 * @param urls 页面 URL 数组
 * @param output 输出文件路径
 * @param options 配置选项
 * @returns Promise<void>
 * 
 * @example
 * ```ts
 * await exportURLsToSinglePage(
 *   [
 *     'http://localhost:5173/guide/intro',
 *     'http://localhost:5173/guide/setup'
 *   ],
 *   './output/guide.html',
 *   {
 *     title: 'User Guide',
 *     inlineStyles: true
 *   }
 * )
 * ```
 */
export async function exportURLsToSinglePage(
  urls: string[],
  output: string,
  options: Partial<SinglePageExportOptions> = {}
): Promise<void> {
  // 动态导入 Playwright
  let playwright: any
  try {
    playwright = await import('playwright')
  } catch (error) {
    throw new Error(
      'Playwright is not installed. Please install it with: npm install -D playwright'
    )
  }

  const browser = await playwright.chromium.launch({ headless: true })
  const pages: PageContent[] = []

  try {
    const context = await browser.newContext()

    for (const url of urls) {
      const page = await context.newPage()

      try {
        await page.goto(url, { waitUntil: 'networkidle' })

        // 提取页面标题和内容
        const pageData = await page.evaluate(() => {
          const titleEl = document.querySelector('h1') || document.querySelector('title')
          const title = titleEl?.textContent?.trim() || 'Untitled'

          // 获取主要内容区域
          const contentEl = document.querySelector('.vp-doc') || document.querySelector('main') || document.body
          const content = contentEl?.innerHTML || ''

          return { title, content }
        })

        pages.push({
          title: pageData.title,
          content: pageData.content,
          url
        })
      } finally {
        await page.close()
      }
    }

    // 导出为单页 HTML
    await exportToSinglePage({
      pages,
      output,
      ...options
    })
  } finally {
    await browser.close()
  }
}
